#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=5

banner "Commit-signing setup"

# Windows: run this script in Git Bash (needs ssh-keygen, git, gh).
# No .env values and no CI secrets: our workflows need neither. Every
# value this wizard captures lands in git config, ~/.ssh, or GitHub.

# ── Stage 1: key ──────────────────────────────────────────────────────
stage "Generate the signing key"
DEFAULT_EMAIL="$(git config user.email || true)"
ask EMAIL "Email for the key comment [${DEFAULT_EMAIL:-you@example.com}]:"
if [[ -z "$EMAIL" && -n "$DEFAULT_EMAIL" ]]; then EMAIL="$DEFAULT_EMAIL"; fi
ask KEY_PATH "Key path [$HOME/.ssh/ai-bank_sign]:"
if [[ -z "$KEY_PATH" ]]; then KEY_PATH="$HOME/.ssh/ai-bank_sign"; fi
if [[ -f "$KEY_PATH" ]]; then
  say "A key already exists at $KEY_PATH — reusing it."
else
  say "ssh-keygen will ask for a passphrase (recommended; use ssh-agent so git stops prompting)."
  mkdir -p "$(dirname "$KEY_PATH")"
  ssh-keygen -t ed25519 -C "$EMAIL" -f "$KEY_PATH"
  say "Keypair created."
fi
note "Public half: $KEY_PATH.pub (safe to share). Private half never leaves this machine."
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 2: registration ─────────────────────────────────────────────
stage "Register the key on GitHub"
PUB="$KEY_PATH.pub"
REGISTERED=false
if gh ssh-key add "$PUB" --type signing --title "commit signing ($(hostname))" >/dev/null 2>&1; then
  REGISTERED=true
  say "Registered via gh."
fi
if ! "$REGISTERED"; then
  warn "gh could not register the key (usually a missing scope)."
  if confirm "Grant the signing-key scope and retry automatically"; then
    if gh auth refresh -s admin:ssh_signing_key; then
      if gh ssh-key add "$PUB" --type signing --title "commit signing ($(hostname))" >/dev/null 2>&1; then
        REGISTERED=true
        say "Registered via gh."
      fi
    else
      warn "scope refresh failed — continuing to manual registration."
    fi
  fi
fi
if ! "$REGISTERED"; then
  warn "falling back to manual registration."
  open_url "https://github.com/settings/ssh/new"
  step "Title: commit signing ($(hostname))"
  step "Key type: switch from Authentication Key to Signing Key."
  step "Key: paste the public key printed below, then click Add SSH key."
  say "----- $PUB -----"
  cat "$PUB"
  say "-------------------------------"
  pause "Press Enter after GitHub confirms the key"
fi
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 3: git config ───────────────────────────────────────────────
stage "Configure git to sign"
git config --global gpg.format ssh
git config --global user.signingkey "$PUB"
git config --global commit.gpgsign true
git config --global tag.gpgsign true
say "gpg.format = $(git config --global --get gpg.format)"
say "user.signingkey = $(git config --global --get user.signingkey)"
say "commit.gpgsign = $(git config --global --get commit.gpgsign)"
say "tag.gpgsign = $(git config --global --get tag.gpgsign)"
note "main already requires signed commits, so every PR from here is covered."
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 4: local trust ──────────────────────────────────────────────
stage "Trust the key for local verification"
mkdir -p "$HOME/.ssh"
SIGNERS="$HOME/.ssh/allowed_signers"
if grep -qF "$EMAIL" "$SIGNERS" 2>/dev/null; then
  say "allowed_signers already has an entry for $EMAIL."
else
  printf '%s\n' "$EMAIL $(cat "$PUB")" >> "$SIGNERS"
  say "Appended $EMAIL to $SIGNERS."
fi
git config --global gpg.ssh.allowedSignersFile "$SIGNERS"
say "allowedSignersFile = $(git config --global --get gpg.ssh.allowedSignersFile)"
# ──────────────────────────────────────────────────────────────────────────

# ── Stage 5: verify ───────────────────────────────────────────────────
stage "Verify end to end"
BASE="$(git branch --show-current)"
DETACHED=false
if [[ -z "$BASE" ]]; then
  DETACHED=true
  ORIG_HEAD="$(git rev-parse HEAD)"
  BASE="main"
fi
BRANCH="probe/signing-$$"
cleanup_probe() {
  if "$DETACHED"; then
    git checkout -q --detach "$ORIG_HEAD" 2>/dev/null || true
  else
    git checkout -q "$BASE" 2>/dev/null || true
  fi
  git branch -q -D "$BRANCH" 2>/dev/null || true
}
if confirm "Push one empty signed commit on scratch branch $BRANCH (deleted afterwards)"; then
  trap cleanup_probe EXIT
  git checkout -q -b "$BRANCH"
  git commit -q --allow-empty -m "probe: commit signing"
  if git verify-commit HEAD >/dev/null 2>&1; then
    say "local signature: good"
  else
    warn "local verification failed — is the key registered and allowed_signers correct?"
    exit 1
  fi
  git push -q origin "$BRANCH"
  REPO="$(gh repo view --json nameWithOwner --jq .nameWithOwner 2>/dev/null || echo kudosscience/ai-bank)"
  if [[ "$(gh api "repos/$REPO/commits/$BRANCH" --jq '.commit.verification.verified')" == "true" ]]; then
    say "GitHub verification: verified=true"
  else
    warn "GitHub does not show the commit as verified — check the key is a Signing Key."
  fi
  git push -q origin --delete "$BRANCH"
  trap - EXIT
  cleanup_probe
  say "Probe branch removed."
else
  say "Skipped verification — re-run this wizard any time to finish it."
fi
# ──────────────────────────────────────────────────────────────────────────

finish
